from typing import List

from pydantic import BaseModel


class TagData(BaseModel):
    """
    Represents a single tag extracted from image analysis.

    This model holds the information about tags identified in an image along with
    a confidence score indicating how certain the analysis is about that tag.

    :param tag: The text label of the identified tag (e.g., "dog", "sunset", "beach")
    :param confidence: A float value between 0.0 and 1.0 representing the model's
                       confidence in this tag being present in the image
    """
    tag: str
    confidence: float

class ColorData(BaseModel):
    """
    Represents a color detected in the analyzed image.

    This model captures color information extracted from images, including
    the specific color name and how frequently it appears in the image.

    :param color: The name or identifier of the detected color (e.g., "blue", "#FF5733")
    :param frequency: A float value between 0.0 and 1.0 representing the relative
                      prominence or frequency of this color in the image
    """
    color: str
    frequency: float

class Metadata(BaseModel):
    """
    Container for image metadata extracted during analysis.

    This model aggregates key descriptive information about an image, including
    its tags, detected colors, and a reference to the thumbnail image.

    :param tags: A comma-separated string of all tags identified in the image
    :param colors: A comma-separated string of all detected colors in the image
    :param thumbnail: The base64-encoded PNG data URI of the image thumbnail
    """
    tags: str
    colors: str
    thumbnail: str

class AnalysisResult(BaseModel):
    """
    Complete analysis result for an image.

    This model contains the full output from the LLM-based image analysis,
    including all detected tags with confidence scores and all colors with frequencies.

    The LLM processes an image and returns structured data about what it sees,
    which is then parsed into this model format for storage and retrieval.

    :param tags: A list of TagData objects, each containing a tag name and confidence score
    :param colors: A list of ColorData objects, each containing a color name and frequency
    :param description: A natural language text summary of the image content generated by the LLM

    :note: This model is used as the response format for LLM image analysis requests
          and serves as the primary data structure for storing analyzed images.
    """
    tags: List[TagData]
    colors: List[ColorData]
    description: str
